---
title: "Impute_HomeCredit"
author: "Hai Long, Le"
date: "4/26/2020"
output: html_document
---

# Import Data and Package

```{r message=FALSE}
library(readr)
library(dplyr)
library(missRanger)
```


```{r message=FALSE}
train <-read_csv("application_train.csv")
```


```{r message=FALSE}
test <-read_csv("application_test.csv")
```



```{r}
library(parallel) 
# Calculate the number of cores
no_cores <- detectCores() - 4

library(doParallel)
# create the cluster for caret to use
cl <- makePSOCKcluster(no_cores)
registerDoParallel(cl)
no_cores
```

```{r}
ID_Train = train$SK_ID_CURR
train <- train %>% select(-SK_ID_CURR)
```


```{r}
ID_Test = test$SK_ID_CURR
test <- test %>% select(-SK_ID_CURR)
```


# Impute Missing Values using RF.


```{r results='hide', message=FALSE, warning=FALSE}
Imputed_Train <- missRanger(train, num.trees = 120, maxiter =2L, verbose = 1)
```


```{r results='hide', message=FALSE, warning=FALSE}
Imputed_Test <- missRanger(test, num.trees = 120, maxiter =2L, verbose = 1)
```



# Checking if Missing.

```{r}
sum(is.na(Imputed_Train))
```

```{r}
sum(is.na(Imputed_Test))
```

```{r}
Imputed_Train <- cbind(ID_Train,Imputed_Train)
```

```{r}
Imputed_Test <- cbind(ID_Test, Imputed_Test)
```



```{r}
write.csv(Imputed_Train, "imputed_application_Train3.csv")
write.csv(Imputed_Test, "imputed_application_Test3.csv")
```




  